### ISSUE TITLE
gulp watch error

### ISSUE THREAD

**Issue by NismoGraphics** [night/BetterTTV#3499]
Tried adding a command just to mess around no errors when using ESLint but get this error when running gulp watch:
`Caught exception:  { AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (D:\Bots\--^--\BetterTTV\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (D:\Bots\--^--\BetterTTV\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (D:\Bots\--^--\BetterTTV\gulpfile.js:62:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }`

**Comment by night** [comment]
Unfortunately I have no idea as I don't use windows as a development machine. CI builds work, and it works locally for me. Make sure you're on Node 6, not latest.
