### ISSUE TITLE
BetterTTV settings can not be accessed from chat settings cog

### ISSUE THREAD

**Issue by ToxicSmurf** [night/betterttv#5598]
Windows 10, Chrome 104. Chat settings popup disappears within seconds of clicking the settings cog. This problem exists while using BetterTTV extension or user script. This problem has existed since installation.

![gif](https://user-images.githubusercontent.com/97206988/187361705-3da7e6d8-c5d4-446e-9703-101941d114a7.gif)

**Comment by dclstn** [comment]
Is there errors in the console after it closes? `CTRL` + `SHIFT` + `I` to open.

**Comment by ToxicSmurf** [comment]
```
betterttv.js:124 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ns (betterttv.js:75:102677)
    at nl (betterttv.js:75:68157)
    at betterttv.js:123:84733
    at betterttv.js:123:84920
    at betterttv.js:123:82606
    at rc (betterttv.js:75:93235)
    at ks (betterttv.js:75:113365)
    at cs (betterttv.js:75:105666)
    at Vo (betterttv.js:75:46671)
    at ks (betterttv.js:75:113507)
    at betterttv.js:75:109969
    at k (betterttv.js:117:1364)
    at MessagePort.M (betterttv.js:117:1896)
(anonymous) @ betterttv.js:124
pl @ betterttv.js:75
n.callback @ betterttv.js:75
za @ betterttv.js:75
bc @ betterttv.js:75
vc @ betterttv.js:75
yc @ betterttv.js:75
(anonymous) @ betterttv.js:75
ws @ betterttv.js:75
cs @ betterttv.js:75
Vo @ betterttv.js:75
ks @ betterttv.js:75
(anonymous) @ betterttv.js:75
k @ betterttv.js:117
M @ betterttv.js:117
betterttv.js:75 Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ns (betterttv.js:75:102677)
    at nl (betterttv.js:75:68157)
    at betterttv.js:123:84733
    at betterttv.js:123:84920
    at betterttv.js:123:82606
    at rc (betterttv.js:75:93235)
    at ks (betterttv.js:75:113365)
    at cs (betterttv.js:75:105666)
    at Vo (betterttv.js:75:46671)
    at ks (betterttv.js:75:113507)
    at betterttv.js:75:109969
    at k (betterttv.js:117:1364)
    at MessagePort.M (betterttv.js:117:1896)
```

**Comment by night** [comment]
What version of Chrome are you using? Have you tried upgrading Chrome?

**Comment by ToxicSmurf** [comment]
This is still a bug, unfortunately.

**Comment by night** [comment]
@ToxicSmurf apologies for the delays as i missed your reply. the minified error doesn't quite help. I suspect you have a bad storage key which is causing the issue. if you clear your cookies I believe it'll fix the issue. however, it would be great to understand why this occurs. Any chance you can open your console and type `JSON.stringify(localStorage)` and then paste the contents of what comes out over to https://gist.github.com for us?

**Comment by ToxicSmurf** [comment]
@night I clear my cookies much too frequently as it is, but after having just tried again I can confirm that does not fix the issue. Here is the gist you asked for https://gist.github.com/ToxicSmurf/4d695b9dd9a3c8e73e56413ef89cf78b

**Comment by night** [comment]
From the stack trace posted above against version 7.4.35 there appears to be an issue occurring in the Table component. I attempted to fix this with https://github.com/night/betterttv/commit/a5fe78c443f1ade0131c2cd09b5a38b0d6445764 but since I am not able to reproduce this issue it's not very clear where it lies. We'll need you to test against the latest version when it releases to see if this helps.

**Comment by night** [comment]
closing this due to inactivity. if the problem still persists, please let us know
