### ISSUE TITLE
[GraphQL] One or more GraphQL errors were detected on request | Point claim failed at the mutation level. Error: failed integrity check

### ISSUE THREAD

**Issue by AndaPlays** [night/betterttv#5735]
If I try to claim Channel Points or submit a Vote I get the following two errors:

`betterttv.js:118 [GraphQL] One or more GraphQL errors were detected on request 01GHEQT2AWR792K54D03YTA0N1. ClaimCommunityPoints: failed integrity check [{…}]`

`betterttv.js:118 6:43:06 PM [ERROR] Point claim failed at the mutation level. Error: failed integrity check
    at new t (vendor-2d4d95de439818e2f227.js:1:205792)
    at vendor-2d4d95de439818e2f227.js:1:185996
    at n (vendor-2d4d95de439818e2f227.js:1:162996)
    at vendor-2d4d95de439818e2f227.js:1:162921
    at new Promise (<anonymous>)
    at Object.then (vendor-2d4d95de439818e2f227.js:1:162887)
    at Object.next (vendor-2d4d95de439818e2f227.js:1:163006)
    at w (vendor-2d4d95de439818e2f227.js:1:1251815)
    at _ (vendor-2d4d95de439818e2f227.js:1:1252321)
    at t.next (vendor-2d4d95de439818e2f227.js:1:1252854)
    at vendor-2d4d95de439818e2f227.js:1:163643
    at Array.forEach (<anonymous>)
    at k (vendor-2d4d95de439818e2f227.js:1:163611)
    at Object.next (vendor-2d4d95de439818e2f227.js:1:164153)
    at w (vendor-2d4d95de439818e2f227.js:1:1251815)
    at _ (vendor-2d4d95de439818e2f227.js:1:1252321)
    at t.next (vendor-2d4d95de439818e2f227.js:1:1252854)
    at vendor-2d4d95de439818e2f227.js:1:220563
    at l (vendor-2d4d95de439818e2f227.js:1:220502)
    at Object.next (vendor-2d4d95de439818e2f227.js:1:220527)
    at w (vendor-2d4d95de439818e2f227.js:1:1251815)
    at _ (vendor-2d4d95de439818e2f227.js:1:1252321)
    at t.next (vendor-2d4d95de439818e2f227.js:1:1252854)
    at Object.a [as next] (core-a20d1a0b2dd87d38ebe5.js:1:1270810)
    at t.<anonymous> (core-a20d1a0b2dd87d38ebe5.js:1:1270574)
    at vendor-2d4d95de439818e2f227.js:1:1120211
    at Object.next (vendor-2d4d95de439818e2f227.js:1:1120316)
    at a (vendor-2d4d95de439818e2f227.js:1:1119055)`

Browser is Brave Version 1.46.99 Chromium: 107.0.5304.91 (Official Build) beta (64-bit)

**Comment by night** [comment]
The error message is misleading. Because BetterTTV tracks error messages it wraps error messages. The error is occuring from Twitch's code according to the stack trace. Unfortunately this appears to be a Twitch issue. You may try clearing your cookies/cache and seeing if that helps.
